version: "3"

services:
  backend:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    container_name: nodejs-backend
    volumes: 
      - "./backend:/usr/app"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: "./frontend"
      dockerfile: Dockerfile
    container_name: nodejs-frontend
    volumes: 
      - "./frontend:/usr/app"
    ports:
      - "3000:3000"
    command: "tail -f /dev/null"