version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-backend
    volumes: 
      - ".:/usr/src/app"
    ports:
      - "3001:3001"
  frontend:
    build:
      context: ../
      dockerfile: ./frontend/Dockerfile
    container_name: nodejs-frontend
    volumes: 
      - "./frontend/.:/usr/src/app"
    ports:
      - "3000:3000"